name: Monthly Email Sender

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  mail-sender:
    runs-on: ubuntu-latest

    steps:
        - name: Send mail
          uses: dawidd6/action-send-mail@v4
          with:
            server_address: smtp.mailersend.net
            server_port: 587
            username: ${{ vars.SMTP_USERNAME }}
            password: ${{ vars.SMTP_PASSWORD }}
            subject: "PODSJETNIK: Platiti mjesečni najam stana"
            to: ${{ vars.RECIPIENT_EMAIL }}
            from: najam@juricamigac.from.hr
            body: ${{ vars.HTML_BODY }}
            cc: ${{ vars.CC_EMAIL }}
            priority: normal