name: Python Script Workflow

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAIL_SUBJECT: ${{ vars.EMAIL_SUBJECT }}
      RECIPIENTS: ${{ vars.EMAIL_SUBJECT }}
      SENDER_EMAIL: ${{ vars.SENDER_EMAIL }}
      SMTP_PASSWORD: ${{ vars.SMTP_PASSWORD }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_SERVER: ${{ vars.SMTP_SERVER }}
      SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"

      - name: Execute Python script # Run the app.py
        run: python app.py
